criaCartao(
' ADIVINHA',
'COMO DEIXAR AGUEM CURIOSO?',
    'EU CONTO AMANHÃ'
)

criaCartao(
    'ADIVINHA',
    'O QUE O TIJOLO FALOU PARA O OUTRO?',
    ' HA UM CIUMENTO ENTRE NOS'
)

criaCartao(
    'ADIVINHA',
    'POR QUE OS ELETRONS NUNCA SAO COVIDADOS PARA FESTA?',
    ' PORQUE ELES SAO MUITO NEGATIVOS!'
)

criaCartao(
    'ADIVINHA',
    'TODO MUNDO TENTA CONVERSAR COM A PLANTA,MAS POR QUE ELA NAO RESPONDE?',
    'PORQUE ELA É MUDINHA!'
)
